# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('ids', models.IntegerField()),
                ('date', models.DateField()),
                ('flag', models.IntegerField()),
                ('user', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
