# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owntweets',
            name='date',
        ),
        migrations.RemoveField(
            model_name='owntweets',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='owntweets',
            name='ids',
        ),
        migrations.RemoveField(
            model_name='owntweets',
            name='user',
        ),
    ]
